// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhj4IJ5lQp_1sBx-kbsUQOIPBJ14a9wzw',
    appId: '1:386871936721:web:c1fb75f448318af0c827f0',
    messagingSenderId: '386871936721',
    projectId: 'login-6f343',
    authDomain: 'login-6f343.firebaseapp.com',
    storageBucket: 'login-6f343.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ND8WrmGZncBV04686qVuec2b634Kjl4',
    appId: '1:386871936721:android:6586a6dedeea1573c827f0',
    messagingSenderId: '386871936721',
    projectId: 'login-6f343',
    storageBucket: 'login-6f343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYgP-kfCx3eJQNPpK5O-PcqR0POWOXoEc',
    appId: '1:386871936721:ios:67f7b9efb12128dbc827f0',
    messagingSenderId: '386871936721',
    projectId: 'login-6f343',
    storageBucket: 'login-6f343.appspot.com',
    iosClientId: '386871936721-udjl2klpvt2allhmn5m6mom14pri0i20.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYgP-kfCx3eJQNPpK5O-PcqR0POWOXoEc',
    appId: '1:386871936721:ios:67f7b9efb12128dbc827f0',
    messagingSenderId: '386871936721',
    projectId: 'login-6f343',
    storageBucket: 'login-6f343.appspot.com',
    iosClientId: '386871936721-udjl2klpvt2allhmn5m6mom14pri0i20.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
